### PR TITLE
[test] Move some to transformers v5

### PR DESCRIPTION
**Pull request by sbalandi**
## Description
GenAI tests are moved to transformers 5.0
Some tests remain on transformers 4.55.4 - `mark.transformers_lower_v5 `
Some tests were divided depending on the cases by models or by sampling(there are fails with goup beam search) - `mark.transformers_dependent`
model for tests/python_tests/samples/test_benchmark_vlm.py, tests/python_tests/samples/test_scheduler_config.py was changed from tiny-random-minicpmv-2_6 to tiny-random-phi3-vision since support of minicpmv are deprecating in transformers v.5 (https://github.com/huggingface/optimum-intel/pull/1589)

Test schema example with new marks:
VLM: transformers_dependent(scope for transformers==5.0)  + **not** transformers_lower_v5 + all other tests
VLM with transformers under 5.0: transformers_dependent(scope for transformers<5.0)  + transformers_lower_v5 + **not** all other tests

Problems for transformers_lower_v5 (not all required tasks):
- CVS-185784 whisper tests, error: KeyError: 'num_frames' 
- CVS-185787 whisper tests, error: Check '!self_attn_nodes.empty()' fails
- CVS-185791 accuracy drop llama
- CVS-185790 - group beam search win/lin
- CVS-185788 accuracy drop for tests with Qwen/Qwen2-0.5B-Instruct
- CVS-186071 test_image_generation_cpu_vs_npuw_cpu_with_blob_model fails
- CVS-186059 (CVS-185793 also, need to close) gemma3, llava-next, llava, error - Add node with name '__module.model.model.vision_tower.vision_model.embeddings/aten::add/Add' Check 'input_shape[j] == 1' failed
- llava-next-video hasn't supported by optimum-intel 423b423 with transformers>=5.0 yet
- version of the speechbrain module compatible with transformers v5.0 causes an import error with k2 module on Windows

Problems for transformers_dependent(the same +):
- CVS-185559 - samples llm tests, conversion of microsoft/phi-1_5 , error - AttributeError: 'PhiConfig' object has no attribute 'pad_token_id'. Did you mean: 'bos_token_id'?
- CVS-185605 - "Tokenizers for draft and main models are different" with optimum-intel 423b423 and transformers>=5.0
- qwen3_next is not supported by optimum-intel 423b423 with transformers>=5.0
- minicpmv, internvl_chat, minicpmo, llava_next_video  is not supported by transformers>=v5

Task:
[CVS-185024](https://jira.devtools.intel.com/browse/CVS-185024)

## Checklist:
- [ ] This PR follows [GenAI Contributing guidelines](https://github.com/openvinotoolkit/openvino.genai?tab=contributing-ov-file#contributing). 
- [ ] Tests have been updated or added to cover the new code. 
- [ ] This PR fully addresses the ticket. 
- [ ] I have made corresponding changes to the documentation.

### CODE REVIEW

File: samples/export-requirements.txt [hunk 1]
```diff
@@ -1,14 +1,14 @@
...
-https://github.com/huggingface/optimum-intel/archive/2c48d6430c265ac259c1b264f3e2c4025cdd7b76.tar.gz#egg=optimum-intel
+https://github.com/huggingface/optimum-intel/archive/f50a0b326df82d4b05c461a9184a97f616bfa63a.tar.gz#egg=optimum-intel
 einops==0.8.2  # For Qwen
 transformers_stream_generator==0.0.5  # For Qwen
 diffusers==0.37.1 # For image generation pipelines
 timm==1.0.26  # For exporting InternVL2
 # torchvision for visual language models
 torchvision==0.26.0
-transformers==4.55.4 # For Whisper
+transformers==5.0.0 # For Whisper
```
Comment (sbalandi) [inline samples/export-requirements.txt]:
```suggestion
transformers==5.0.0
```

File: tools/llm_bench/llm_bench_utils/llm_hook_sample/hook_sample_v5_3.py [hunk 2]
```diff
@@ -238,6 +238,7 @@ def new_sample(
         else self.__call__
     )
 
+    tic_infer = time.perf_counter()
```
Comment (sbalandi) [inline tools/llm_bench/llm_bench_utils/llm_hook_sample/hook_sample_v5_3.py]:
```suggestion
```

File: tools/llm_bench/llm_bench_utils/llm_hook_sample/hook_sample_v5_3.py [hunk 3]
```diff
@@ -312,6 +313,7 @@ def new_sample(
 
         unfinished_sequences = unfinished_sequences & ~stopping_criteria(input_ids, scores)
         this_peer_finished = unfinished_sequences.max() == 0
+        hook_greedy.tm_list.append(time.perf_counter() - tic)
```
Comment (sbalandi) [inline tools/llm_bench/llm_bench_utils/llm_hook_sample/hook_sample_v5_3.py:344]:
```suggestion
```

File: tools/who_what_benchmark/requirements.txt [hunk 4]
```diff
@@ -19,7 +19,7 @@ scikit-image<=0.26.0
 # - openbmb/MiniCPM-o-2_6
 soundfile==0.13.1
 librosa==0.11.0
-torchcodec<=0.11.0; sys_platform == "linux"
+# torchcodec<=0.11.0; sys_platform == "linux"
```
Comment (sbalandi) [inline tools/who_what_benchmark/requirements.txt]:
```suggestion
```

File: .github/workflows/linux.yml [hunk 5]
```diff
@@ -586,15 +592,29 @@ jobs:
...
             timeout: 360
           - name: 'LLM'
-            cmd: 'python -m pytest -v ./tests/python_tests/test_llm_pipeline.py tests/python_tests/test_llm_pipeline_static.py tests/python_tests/test_structured_output.py tests/python_tests/test_image_generation.py tests/python_tests/test_image_generation_multi_call.py --override-ini cache_dir=/mount/caches/pytest/'
+            cmd: 'python -m pytest -v ./tests/python_tests/test_llm_pipeline.py tests/python_tests/test_llm_pipeline_static.py tests/python_tests/test_structured_output.py tests/python_tests/test_image_generation.py tests/python_tests/test_image_generation_multi_call.py -k "not transformers_lower_v5" --override-ini cache_dir=/mount/caches/pytest/'
+            run_condition: ${{ fromJSON(needs.smart_ci.outputs.affected_components).LLM.test || fromJSON(needs.smart_ci.outputs.affected_components).Image_generation.test }}
+            timeout: 90
+          - name: 'LLM with transformers under 5.0'
+            cmd: |
+              python -m pip install transformers==4.55.4
+              python -m pip install --no-deps git+https://github.com/huggingface/optimum-intel.git@2c48d6430c265ac259c1b264f3e2c4025cdd7b76
```
Comment (as-suvorov) [inline .github/workflows/linux.yml:601]: Can we use transformers tag here instead of commit hash? Or add tag as a comment

File: .github/workflows/linux.yml [hunk 6]
```diff
@@ -586,15 +592,29 @@ jobs:
...
+              python -m pytest -v ./tests/python_tests/test_llm_pipeline.py -k "transformers_lower_v5 or transformers_dependent" --override-ini cache_dir=/mount/caches/pytest/
```
Comment (as-suvorov) [inline .github/workflows/linux.yml]: Please explain what `mark.transformers_dependent` mean?

File: samples/c/whisper_speech_recognition/README.md [hunk 7]
```diff
@@ -48,13 +48,13 @@ pip install --upgrade-strategy eager -r ../../export-requirements.txt
...
 
-If a converted model in OpenVINO IR format is available in the [OpenVINO optimized models](https://huggingface.co/OpenVINO) collection on Hugging Face, you can download it directly via huggingface-cli.
+If a converted model in OpenVINO IR format is available in the [OpenVINO optimized models](https://huggingface.co/OpenVINO) collection on Hugging Face, you can download it directly via hf
 
 For example:
 
 ```sh
 pip install huggingface-hub
-huggingface-cli download OpenVINO/whisper-tiny-int8-ov --local-dir whisper-tiny-int8-ov
+hf download OpenVINO/whisper-tiny-int8-ov --local-dir whisper-tiny-int8-ov
```
Comment (as-suvorov) [inline samples/c/whisper_speech_recognition/README.md:57]: tool name changed with `1.0` release, right?

File: tests/python_tests/data/test_dataset.py [hunk 8]
```diff
@@ -12,11 +13,19 @@ def get_test_dataset() -> tuple[list[str], list[GenerationConfig]]:
...
-        get_greedy(),
-        get_beam_search(),
-    ]
+    if is_transformers_version("<", "5.0"):
+        generation_configs = [
+            get_beam_search(),
+            get_beam_search(),
+            get_beam_search(),
+            get_beam_search(),
+        ]
```
Comment (as-suvorov) [inline tests/python_tests/data/test_dataset.py:15]:
```suggestion
        generation_configs = [
            get_greedy(),
            get_beam_search(),
            get_greedy(),
            get_beam_search(),
        ]
```

File: tests/python_tests/samples/test_beam_search_causal_lm.py [hunk 9]
```diff
@@ -97,9 +122,24 @@ def test_sample_beam_search_causal_lm_refs(self, request, convert_model, sample_
...
+                "num_beams": 15,
+                "num_return_sequences": 15,
+                "diversity_penalty": 1.0,
+                "max_new_tokens": 20,
+                "early_stopping": False,
+                "length_penalty": 1.0,
+                "no_repeat_ngram_size": 9**9,
+                "do_sample": False,
+            }
+            if is_transformers_version(">=", "5.0"):
```
Comment (as-suvorov) [inline tests/python_tests/samples/test_beam_search_causal_lm.py:139]: test marked as `@pytest.mark.transformers_lower_v5` why this check is here?

File: tests/python_tests/samples/test_encrypted_model_vlm.py [hunk 10]
```diff
@@ -13,11 +13,15 @@
 class TestEncryptedVLM:
     @pytest.mark.llm
     @pytest.mark.samples
+    @pytest.mark.transformers_lower_v5
```
Comment (as-suvorov) [inline tests/python_tests/samples/test_encrypted_model_vlm.py]: Why mark is here? Model changed to `tiny-random-phi3-vision` so test should work?

File: tests/python_tests/samples/test_greedy_causal_lm.py [hunk 11]
```diff
@@ -6,27 +6,41 @@
 
 from conftest import logger, MODELS, SAMPLES_PY_DIR, SAMPLES_CPP_DIR, SAMPLES_C_DIR, SAMPLES_JS_DIR
 from test_utils import run_sample
+from optimum.intel.utils.import_utils import is_transformers_version
+
+
+GREEDY_MODEL_LIST = []
+if is_transformers_version("<", "5.0"):
```
Comment (as-suvorov) [inline tests/python_tests/samples/test_greedy_causal_lm.py:13]: why splitting needed for greedy decoding?

File: tests/python_tests/utils/constants.py [hunk 12]
```diff
@@ -18,12 +19,20 @@ def get_default_llm_properties():
...
 
-def extra_generate_kwargs():
+def extra_generate_kwargs(generation_config: HFGenerationConfig = None):
     from optimum.intel.utils.import_utils import is_transformers_version
     additional_args = {}
-    if is_transformers_version(">=", "4.51"):
+    if is_transformers_version(">=", "4.51") and is_transformers_version("<", "5.0"):
         additional_args["use_model_defaults"] = False
 
+    if is_transformers_version(">=", "4.51") and (
```
Comment (as-suvorov) [inline tests/python_tests/utils/constants.py:28]:
```suggestion
    if is_transformers_version(">=", "4.51") and is_transformers_version("<", "5.0"):
additional_args["use_model_defaults"] = False

    elif is_transformers_version(">=", "5.0") and (
```

File: tests/python_tests/test_continuous_batching.py [hunk 13]
```diff
@@ -362,19 +367,30 @@ def get_beam_search_seq_len_300() -> GenerationConfig:
...
 
 
-@pytest.mark.parametrize(
-    "params", 
-    [
-        ({"num_kv_blocks": 2, "dynamic_split_fuse": True, "max_num_batched_tokens": 256, "max_num_seqs": 256}, get_greedy()),
-        ({"num_kv_blocks": 2, "dynamic_split_fuse": False, "max_num_batched_tokens": 256, "max_num_seqs": 256}, get_greedy()),
-        ({"num_kv_blocks": 10, "dynamic_split_fuse": True}, get_parallel_sampling_seq_len_300()),
-        ({"num_kv_blocks": 10, "dynamic_split_fuse": False}, get_parallel_sampling_seq_len_300()),
+if is_transformers_version("<", "5.0"):
```
Comment (as-suvorov) [inline tests/python_tests/test_continuous_batching.py:374]: I guess for such cases ticket number should be added as well

**Review by as-suvorov — COMMENTED** [review]
Should we add tickets numbers for tests marked as `@pytest.mark.transformers_lower_v5`?
It would be simpler to enable tests back

File: .github/workflows/linux.yml (hunk 6 above)
Comment (sbalandi) [reply .github/workflows/linux.yml]: Some tests only work with transformer versions below 5, such tests were warked with transformers_lower_v5. Some tests have cases that work with version 5.0, while others cases only work with transformers of lower versions. These tests were divided based on models/sampling by condition is_transformers_version("<", "5.0") and maked as transformer_dependent.

File: samples/c/whisper_speech_recognition/README.md (hunk 7 above)
Comment (sbalandi) [reply samples/c/whisper_speech_recognition/README.md:57]: `hf` was introduced in `0.34` https://pypi.org/project/huggingface-hub/0.34.0/ , but `huggingface-cli` was deprecated starting `1.0`

File: tests/python_tests/samples/test_beam_search_causal_lm.py (hunk 9 above)
Comment (sbalandi) [reply tests/python_tests/samples/test_beam_search_causal_lm.py:139]: it was hope

Comment (sbalandi) [reply tests/python_tests/samples/test_beam_search_causal_lm.py:139]: But I would leave this logic because there were two points here. First - this logic is needed for beam search, but the test is currently failing anyway on new 5.0 transformers due to the llama architecture. I'll attach the task.

File: tests/python_tests/samples/test_encrypted_model_vlm.py (hunk 10 above)
Comment (sbalandi) [reply tests/python_tests/samples/test_encrypted_model_vlm.py]: It's not needed here, the test failed because of this error `AttributeError: 'DynamicCache' object has no attribute 'get_usable_length'. Ticket CVS-175110`  , I think I need to find a another model, I'll replace it. Thank you ! I didn't notice that the model was replaced by me

File: tests/python_tests/utils/constants.py (hunk 12 above)
Comment (sbalandi) [reply tests/python_tests/utils/constants.py:28]: do you mean that 
```
        additional_args["trust_remote_code"] = True
        additional_args["do_sample"] = False
```
should be added for transformers >= 5.0 only ?

File: tests/python_tests/data/test_dataset.py (hunk 8 above)
Comment (sbalandi) [reply tests/python_tests/data/test_dataset.py:15]: I would like to reduce duplicate, so I will update the prompts.

File: .github/workflows/linux.yml (hunk 5 above)
Comment (sbalandi) [reply .github/workflows/linux.yml:601]: what tag do you mean ? commit hash for optimum-intel https://github.com/huggingface/optimum-intel/commit/2c48d6430c265ac259c1b264f3e2c4025cdd7b76 - what tag I can use from this commit ?

File: tests/python_tests/samples/test_greedy_causal_lm.py (hunk 11 above)
Comment (sbalandi) [reply tests/python_tests/samples/test_greedy_causal_lm.py:13]: models fails, have added the comments

File: .github/workflows/windows.yml [hunk 14]
```diff
@@ -662,9 +662,15 @@ jobs:
...
+            cmd: |
+              python -m pytest -s -v tests/python_tests/test_whisper_pipeline.py tests/python_tests/test_whisper_pipeline_static.py -k "not transformers_lower_v5 and not test_smoke[sample_from_dataset0 and not test_whisper_constructors[sample_from_dataset0 and not test_max_new_tokens[sample_from_dataset0 and not test_language_mode[language and not test_task_mode[sample_from_dataset0 and not test_language_autodetect[sample_from_dataset0 and not test_whisper_config_constructor and not test_language_autodetect[sample_from_dataset1 and not test_language_autodetect[sample_from_dataset2 and not test_initial_prompt_hotwords[sample_from_dataset0 and not test_random_sampling[sample_from_dataset0"
             run_condition: ${{ fromJSON(needs.smart_ci.outputs.affected_components).whisper.test }}
             timeout: 120
+          - name: 'Whisper Transformers under 5.0'
+            cmd: |
+              python -m pip install transformers==4.55.4
+              python -m pytest -v ./tests/python_tests/test_whisper_pipeline.py ./tests/python_tests/test_whisper_pipeline_static.py -k "transformers_lower_v5"
+            timeout: 120
```
[the remark this answers is not in the document]
Comment (sbalandi) [reply .github/workflows/windows.yml:673]: moved

File: .github/workflows/linux.yml (hunk 5 above)
Comment (as-suvorov) [reply .github/workflows/linux.yml:601]: Sometimes there can be tags like `transformers-5.5` which we can use as a version to install. Not in this case, let's leave hash as is.

File: .github/workflows/linux.yml (hunk 6 above)
Comment (as-suvorov) [reply .github/workflows/linux.yml]: From your explanation I understood there are 2 groups - < 5.0 and >= 5.0. So single mark `transformers_lower_v5` should be enough

File: tests/python_tests/samples/test_beam_search_causal_lm.py (hunk 9 above)
Comment (as-suvorov) [reply tests/python_tests/samples/test_beam_search_causal_lm.py:139]: Test marked as `@pytest.mark.transformers_lower_v5`. I would expect it runs strictly with transformers `< 5.0`. So no need to check if transformers version `>= 5.0` inside the test.

**Comment by sbalandi** [comment]
@as-suvorov could you please take a look ?

**Comment by as-suvorov** [comment]
> @as-suvorov could you please take a look ?

There are unresolved comments from first review, please reply to them first

**Review by as-suvorov — APPROVED** [review]
